name: Reusable Release

on:
  workflow_call:
    inputs:
      version-name:
        description: 'Version name (defaults to gradle.properties)'
        required: false
        type: string
      release-body:
        description: 'Release notes (defaults to CHANGELOG.md)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Version
        run: |
          if [ -n "${{ inputs.version-name }}" ]; then
            echo "Using provided version: ${{ inputs.version-name }}"
            echo "VERSION_NAME=${{ inputs.version-name }}" >> $GITHUB_ENV
          else
            VERSION_NAME=$(grep '^VERSION_NAME=' gradle.properties | cut -d'=' -f2)
            echo "Using version from gradle.properties: $VERSION_NAME"
            echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          fi
          echo "Version: $VERSION_NAME"

      - name: Get Release Notes
        run: |
          if [ -n "${{ inputs.release-body }}" ]; then
              echo "Using provided release body"
              RAW_BODY='${{ inputs.release-body }}'
              RELEASE_BODY=$(echo "$RAW_BODY" | sed 's/ - /\n- /g; s/ \* /\n* /g')
              {
                echo "RELEASE_BODY<<EOF"
                echo "$RELEASE_BODY"
                echo "EOF"
              } >> $GITHUB_ENV
          else
              RELEASE_BODY=$(awk '/^####/{if(f)exit; f=1; next} f' CHANGELOG.md)
              echo "Using release notes from CHANGELOG.md"
              {
                echo "RELEASE_BODY<<EOF"
                echo "$RELEASE_BODY"
                echo "EOF"
              } >> $GITHUB_ENV
          fi
          echo "Release notes:"
          echo "$RELEASE_BODY"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_NAME }}
          name: ${{ env.VERSION_NAME }}
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
