name: Reusable Build

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version (takes precedence over java-version-file)'
        required: false
        type: string
        default: '' 
      java-version-file:
        description: 'Path to the .java-version or .sdkmanrc file.'
        required: false
        type: string
        default: ''
      gradle-command:
        description: 'Gradle command to execute (default: ./gradlew build)'
        required: false
        type: string
        default: './gradlew build'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
          java-version-file: ${{ inputs.java-version-file }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ${{ inputs.gradle-command }}